export Discord from 'assets/Discord.svg';
export Spotify from 'assets/Spotify.svg';
export Twitter from 'assets/Twitter.svg';
export Website from 'assets/Website.svg';
export YouTube from 'assets/YouTube.svg';
export GitHub  from 'assets/GitHub.svg';
export GitLab  from 'assets/GitLab.svg';
export Reddit  from 'assets/Reddit.svg';
export Twitch  from 'assets/Twitch.svg';
